colors:
  primary:
    background: '#23252e'
    forground: '#ffffff'
    bright_background: '#23252e'
    bright_forground: '#ffffff'
  normal:
    black: '#1f2229'
    red: '#d41919'
    green: '#5ebdab'
    yellow: '#fea44c'
    blue: '#367bf0'
    magenta: '#9755b3'
    cyan: '#49aee6'
    white: '#e6e6e6'
  bright:
    black: '#198388'
    red: '#ec0101'
    green: '#47d4b9'
    yellow: '#ff8a18'
    blue: '#277fff'
    magenta: '#962ac3'
    cyan: '#05a1f7'
    white: '#ffffff'
  transparent_background_colors: true

cursor:
  style:
    blinking: Always

draw_bold_text_with_bright_colors: true

env:
  TERM: xterm-256color

font:
  normal:
    family: Overpass Mono
  size: 12.0

key_bindings:
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: Return, mods: Control, action: ToggleFullscreen }

mouse:
  hide_when_typing: true

window:
  opacity: 0.9
  padding:
    x: 4
    y: 2
  startup_mode: Maximized
