colors:
  transparent_background_colors: true
cursor:
  style:
    blinking: Always
draw_bold_text_with_bright_colors: true
env:
  TERM: xterm-256color
font:
  normal:
    family: SF Mono
  size: 12.0
import:
  - ~/.config/alacritty/themes/kali-dark.yml
key_bindings:
  - {action: SpawnNewInstance, key: N, mods: Control|Shift}
  - {action: ToggleFullscreen, key: Back, mods: Control}
  - {action: Copy, key: C, mods: Control|Shift}
  - {action: Paste, key: V, mode: ~Vi, mods: Control|Shift}
mouse:
  hide_when_typing: true
window:
  opacity: 0.9
  option_as_alt: Both
  padding:
    x: 4
    y: 2
  startup_mode: Maximized
