colors:
  bright:
    black: '#198388'
    blue: '#277fff'
    cyan: '#05a1f7'
    green: '#47d4b9'
    magenta: '#962ac3'
    red: '#ec0101'
    white: '#ffffff'
    yellow: '#ff8a18'
  normal:
    black: '#1f2229'
    blue: '#367bf0'
    cyan: '#49aee6'
    green: '#5ebdab'
    magenta: '#9755b3'
    red: '#d41919'
    white: '#e6e6e6'
    yellow: '#fea44c'
  primary:
    background: '#23252e'
    bright_background: '#23252e'
    bright_forground: '#ffffff'
    forground: '#ffffff'
  transparent_background_colors: true
cursor:
  style:
    blinking: Always
draw_bold_text_with_bright_colors: true
env:
  TERM: xterm-256color
font:
  normal:
    family: SF Mono
  size: 12.0
key_bindings:
  - {action: SpawnNewInstance, key: N, mods: Control|Shift}
  - {action: ToggleFullscreen, key: Back, mods: Control}
  - {action: Copy, key: C, mods: Control|Shift}
  - {action: Paste, key: V, mode: ~Vi, mods: Control|Shift}
mouse:
  hide_when_typing: true
window:
  opacity: 0.9
  option_as_alt: Both
  padding:
    x: 4
    y: 2
  startup_mode: Maximized
