env:
  TERM: xterm-256color

font:
  normal:
    family: Overpass Mono
  size: 12.0

key_bindings:
  - { key: N, mods: Shift|Control, action: SpawnNewInstance }

mouse:
  hide_when_typing: true

window:
  opacity: 0.9
  padding:
    x: 4
    y: 2
  startup_mode: Maximized
