import = ["~/.config/alacritty/themes/modus-vivendi.toml"]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "SF Mono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[window]
opacity = 0.8
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 4
y = 2
