- name: nginx
  hosts: nginx
  become: yes
  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
  tasks:
    - name: pull cert
      get_url:
        url: "{{ api_endpoint }}/{{ nginx_tls_domain }}/{{ item.src }}?raw=true"
        headers:
          Authorization: "{{ auth_token }}"
        dest: "/etc/nginx/pack/certs/{{ nginx_tls_domain }}/{{ item.dst }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      notify: reload nginx
      with_items:
        - src: cert.pem
          dst: fullchain.pem
          mode: "0644"
        - src: key.pem
          dst: privkey.pem
          mode: "0600"
- name: minio
  hosts: minio
  become: yes
  handlers:
    - name: reload minio
      command: docker restart minio
  tasks:
    - name: pull cert
      get_url:
        url: "{{ api_endpoint }}/{{ minio_tls_domain }}/{{ item.src }}?raw=true"
        headers:
          Authorization: "{{ auth_token }}"
        dest: "/srv/minio/certs/{{ item.dst }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      notify: reload minio
      with_items:
        - src: cert.pem
          dst: public.crt
          mode: "0644"
        - src: key.pem
          dst: private.key
          mode: "0600"
- name: gotify
  hosts: gotify
  become: yes
  handlers:
    - name: reload gotify
      command: docker restart gotify
  tasks:
    - name: pull cert
      get_url:
        url: "{{ api_endpoint }}/{{ gotify_tls_domain }}/{{ item.src }}?raw=true"
        headers:
          Authorization: "{{ auth_token }}"
        dest: "/srv/gotify/certs/{{ item.dst }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      notify: reload gotify
      with_items:
        - src: cert.pem
          dst: public.crt
          mode: "0644"
        - src: key.pem
          dst: private.key
          mode: "0600"
