FreeBSD-ports: { enabled: no }
FreeBSD-ports-kmods: { enabled: no }

FreeBSD: {
  #url: "https://pkg.freebsd.org/${ABI}/latest",
  url: "https://mirrors.ustc.edu.cn/freebsd-pkg/${ABI}/latest",
  mirror_type: "none",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}
FreeBSD-kmods: {
  #url: "https://pkg.freebsd.org/${ABI}/kmods_latest_${VERSION_MINOR}",
  url: "https://mirrors.ustc.edu.cn/freebsd-pkg/${ABI}/kmods_latest_${VERSION_MINOR}",
  mirror_type: "none",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}
