autoDirectNodeRoutes: true
bandwidthManager:
  bbr: true
  enabled: true
bpf:
  masquerade: true
cluster:
  name: default
enableIPv6BIGTCP: true
enableIPv6Masquerade: false
hubble:
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - flow
      - flows-to-world
      - httpV2
      - icmp
      - port-distribution
      - tcp
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.24.0.0/16
ipv6:
  enabled: true
ipv6NativeRoutingCIDR: fd00:ebee:10:2400::/56
k8sServiceHost: k8s.internal.cncf.site
k8sServicePort: 6443
kubeProxyReplacement: strict
loadBalancer:
  #acceleration: native
  mode: hybrid
operator:
  prometheus:
    enabled: true
  replicas: 1
prometheus:
  enabled: true
tunnel: disabled
