autoDirectNodeRoutes: true
bandwidthManager:
  bbr: true
  enabled: true
bpf:
  masquerade: true
cluster:
  name: default
enableIPv6BIGTCP: true
endpointRoutes:
  enabled: true
envoy:
  enabled: true
  prometheus:
    serviceMonitor:
      enabled: true
hubble:
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - flow
      - flows-to-world
      - httpV2
      - icmp
      - port-distribution
      - tcp
    serviceMonitor:
      enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
ingressController:
  enabled: true
  loadbalancerMode: shared
  service:
    insecureNodePort: 30080
    secureNodePort: 30443
    type: NodePort
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.24.0.0/16
ipv6:
  enabled: true
ipv6NativeRoutingCIDR: fd00:ebee:10:2400::/56
k8sServiceHost: k8s.internal.cncf.site
k8sServicePort: 6443
kubeProxyReplacement: "true"
loadBalancer:
  #acceleration: native
  mode: snat
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 1
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
rollOutCiliumPods: true
socketLB:
  hostNamespaceOnly: true
tunnel: disabled
