#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# shellcheck disable=SC1090
source "$(dirname "$(dirname "$(realpath "${0}")")")/.privacy/route.cfg"

##

echo iptables -t nat -I PREROUTING -p tcp --dport "${HOST_PORT}" -j DNAT --to "${GUEST_IP}":"${GUEST_PORT}"
echo iptables -t filter -I FORWARD -p tcp -d "${GUEST_IP}" --dport "${GUEST_PORT}" -j ACCEPT

echo iptables -t nat -C PREROUTING -p tcp --dport "${HOST_PORT}" -j DNAT --to "${GUEST_IP}":"${GUEST_PORT}"
echo iptables -t filter -C FORWARD -p tcp -d "${GUEST_IP}" --dport "${GUEST_PORT}" -j ACCEPT

echo iptables -t nat -D PREROUTING -p tcp --dport "${HOST_PORT}" -j DNAT --to "${GUEST_IP}":"${GUEST_PORT}"
echo iptables -t filter -D FORWARD -p tcp -d "${GUEST_IP}" --dport "${GUEST_PORT}" -j ACCEPT

echo iptables -t nat -L PREROUTING -n -v --line-numbers
echo iptables -t filter -L FORWARD -n -v --line-numbers

####

echo iptables \
    --table nat \
    --insert PREROUTING \
    --protocol tcp --dport "${HOST_PORT}" \
    --jump DNAT --to "${GUEST_IP}":"${GUEST_PORT}"

echo iptables \
    --table filter \
    --insert FORWARD \
    --protocol tcp --destination "${GUEST_IP}" --dport "${GUEST_PORT}" \
    --jump ACCEPT

echo iptables \
    --table nat \
    --check PREROUTING \
    --protocol tcp --dport "${HOST_PORT}" \
    --jump DNAT --to "${GUEST_IP}":"${GUEST_PORT}"

echo iptables \
    --table filter \
    --check FORWARD \
    --protocol tcp --destination "${GUEST_IP}" --dport "${GUEST_PORT}" \
    --jump ACCEPT

echo iptables \
    --table nat \
    --delete PREROUTING \
    --protocol tcp --dport "${HOST_PORT}" \
    --jump DNAT --to "${GUEST_IP}":"${GUEST_PORT}"

echo iptables \
    --table filter \
    --delete FORWARD \
    --protocol tcp --destination "${GUEST_IP}" --dport "${GUEST_PORT}" \
    --jump ACCEPT

echo iptables \
    --table nat \
    --list PREROUTING \
    --numeric \
    --verbose \
    --line-numbers

echo iptables \
    --table filter \
    --list FORWARD \
    --numeric \
    --verbose \
    --line-numbers
