#!/bin/bash

if (( EUID != 0 )); then
    echo "✗ This script must be run as root" 1>&2
    exit 1
fi

NAME='prometheus'

if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
    docker container stop "${NAME}"
    docker container rm --volumes "${NAME}"
fi

docker run \
    --detach \
    --hostname xyz \
    --label maintainer=sysadmin@local.domain \
    --name "${NAME}" \
    --network cluster \
    --publish 172.24.0.1:9090:9090 \
    --restart always \
    --volume /srv/prometheus/data:/prometheus \
    --volume /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml \
    prom/prometheus

docker image prune --force
docker container logs "${NAME}"
