#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

docker network create \
    --driver=bridge \
    --gateway=172.24.0.1 \
    --subnet=172.24.0.0/16 \
    cluster
