#!/bin/bash

if (( EUID != 0 )); then
    echo "✗ This script must be run as root" 1>&2
    exit 1
fi

NAME='coredns'

if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
    docker container stop "${NAME}"
    docker container rm --volumes "${NAME}"
fi

docker run \
    --detach \
    --hostname xyz \
    --label maintainer=sysadmin@local.domain \
    --name "${NAME}" \
    --network cluster \
    --publish 127.0.0.1:53:53/udp \
    --publish 172.24.0.1:53:53/udp \
    --publish 172.24.0.1:9153:9153 \
    --publish 53:53/tcp \
    --publish '[::1]:53:53/udp' \
    --restart always \
    --volume /srv/coredns/Corefile:/Corefile \
    --volume /srv/coredns/zones:/zones \
    coredns/coredns

docker image prune --force
docker container logs "${NAME}"
