#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR

if (( EUID != 0 )); then
    echo '✗ This script must be run as root' 1>&2
    exit 1
fi

while (( $# > 0 )); do
    case ${1} in
    -h | --help)
        cat << EOF
Usage:
    ${0##*/} [OPTION]...

Optional arguments:
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

if (( $# > 0 )); then
    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
    exit 1
fi

FORMAT=

FORMAT+='{{printf "%s\n\n" .Name}}'

FORMAT+='{{range .IPAM.Config}}'
FORMAT+='{{printf "\t%s\n" .Gateway}}'
FORMAT+='{{printf "\t%s\n" .Subnet}}'
FORMAT+='{{end}}'

FORMAT+='{{range .Containers}}'
FORMAT+='{{printf "\t%s\t\t%s\n" .IPv4Address .Name}}'
FORMAT+='{{end}}'

docker network inspect cluster --format "${FORMAT}"

FORMAT='{{if .Ports}}{{printf "\t%-16s\t%s" .Names .Ports}}{{end}}'

docker container ls --format "${FORMAT}" --no-trunc | awk 'NF' | sort
