#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

docker run \
    --hostname xyz \
    --label maintainer=sysadmin@local.domain \
    --name mirror \
    --publish 8000:80 \
    --rm \
    --volume ${PWD}:/usr/share/nginx/html \
    --volume /srv/nginx/default.conf:/etc/nginx/conf.d/default.conf \
    nginx
