#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

NAME='minio'

if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
    docker container stop "${NAME}"
    docker container rm --volumes "${NAME}"
fi

docker run \
    --detach \
    --hostname xyz \
    --label maintainer=sysadmin@local.domain \
    --name "${NAME}" \
    --network cluster \
    --publish 256:9000 \
    --restart always \
    --volume /srv/minio:/root/.minio \
    --volume /srv/s3:/data \
    minio/minio server --json /data

docker image prune --force
docker container logs "${NAME}"
