#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

if [ -n "$(docker container ls --all --filter name='^/coredns$' --format '.')" ]; then
    docker container stop coredns
    docker container rm --volumes coredns
fi

docker run \
    --detach \
    --hostname xyz \
    --ip 172.24.0.127 \
    --label maintainer=sysadmin@local.domain \
    --name coredns \
    --network cluster \
    --publish 127.0.0.1:53:53/udp \
    --publish 172.24.0.1:53:53/udp \
    --publish 172.24.0.1:9153:9153 \
    --publish 53:53/tcp \
    --publish [::1]:53:53/udp \
    --restart always \
    --volume /srv/coredns/Corefile:/Corefile \
    --volume /srv/coredns/zones:/zones \
    coredns/coredns

docker image prune --force
docker container logs coredns
