#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

NAME='grafana'

if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
    docker container stop "${NAME}"
    docker container rm --volumes "${NAME}"
fi

docker run \
    --detach \
    --env 'GF_SECURITY_ADMIN_PASSWORD=Prometheus' \
    --env 'TZ='"$(cat /etc/timezone)" \
    --hostname xyz \
    --label maintainer=sysadmin@local.domain \
    --name "${NAME}" \
    --network cluster \
    --publish 127:3000 \
    --restart always \
    --volume /srv/grafana/data:/var/lib/grafana \
    --volume /srv/grafana/grafana.ini:/etc/grafana/grafana.ini \
    grafana/grafana

docker image prune --force
docker container logs "${NAME}"
