#!/bin/bash

if (( EUID != 0 )); then
    echo "✗ This script must be run as root" 1>&2
    exit 1
fi

NAME='v2ray'

if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
    docker container stop "${NAME}"
    docker container rm --volumes "${NAME}"
fi

docker run \
    --detach \
    --hostname xyz \
    --label maintainer=sysadmin@local.domain \
    --name "${NAME}" \
    --network cluster \
    --publish 6666:6666 \
    --restart always \
    --volume /srv/v2ray/config.json:/etc/v2ray/config.json \
    v2ray/official v2ray -config=/etc/v2ray/config.json

docker image prune --force
docker container logs "${NAME}"
