#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR

if (( EUID != 0 )); then
    echo '✗ This script must be run as root' 1>&2
    exit 1
fi

while (( $# > 0 )); do
    case "${1}" in
    -h | --help)
        cat << EOF
Usage:
    ${0##*/} [OPTION]...

Optional arguments:
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

if (( $# > 0 )); then
    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
    exit 1
fi

FORMAT=''

FORMAT+='\n'
FORMAT+='[ {{.Names}} ]\n'
FORMAT+='\n'
FORMAT+='\t- Image: {{.Image}}\n'
FORMAT+='\t- Status: {{.Status}}\n'
FORMAT+='\t- RunningFor: {{.RunningFor}}\n'
FORMAT+='\t- Networks: {{.Networks}}\n'
FORMAT+='\t- Ports: {{.Ports}}\n'
FORMAT+='\t- Mounts: {{.Mounts}}\n'
FORMAT+='\t- Command: {{.Command}}'

docker container ls --format "${FORMAT}" --no-trunc
