#!/bin/bash

if (( EUID != 0 )); then
    echo "✗ This script must be run as root" 1>&2
    exit 1
fi

NAME='mqtt-broker'

if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
    docker container stop "${NAME}"
    docker container rm --volumes "${NAME}"
fi

docker run \
    --detach \
    --hostname xyz \
    --label maintainer=sysadmin@local.domain \
    --name "${NAME}" \
    --network cluster \
    --publish 1883:1883 \
    --restart always \
    --volume /srv/mqtt-broker:/mosquitto/config \
    eclipse-mosquitto

docker image prune --force
docker container logs "${NAME}"
