#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

warn () {
    if (( $# > 0 )); then
        echo "${@}" 1>&2
    fi
}

die () {
    warn "${@}"
    exit 1
}

notify () {
    local code=$?
    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
}

trap notify ERR

if (( EUID != 0 )); then
    die '✗ This script must be run as root'
fi

display_help () {
    cat << EOF
Synopsis:
    ${0##*/} [OPTION]...

Options:
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
}

while (( $# > 0 )); do
    case ${1} in
    -h | --help)
        display_help
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

if (( $# > 0 )); then
    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
fi

clean_up () {
    true
}

trap clean_up EXIT

FORMAT=

FORMAT+='\n'
FORMAT+='[ {{.Names}} ]\n'
FORMAT+='\n'
FORMAT+='\t- Image: {{.Image}}\n'
FORMAT+='\t- Status: {{.Status}}\n'
FORMAT+='\t- RunningFor: {{.RunningFor}}\n'
FORMAT+='\t- Networks: {{.Networks}}\n'
FORMAT+='\t- Ports: {{.Ports}}\n'
FORMAT+='\t- Mounts: {{.Mounts}}\n'
FORMAT+='\t- Command: {{.Command}}'

docker container ls --format "${FORMAT}" --no-trunc
