#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

if [ -n "$(docker container ls --all --filter name='^/v2ray$' --format '.')" ]; then
    docker container stop v2ray
    docker container rm --volumes v2ray
fi

docker run \
    --detach \
    --hostname xyz \
    --ip 172.24.0.128 \
    --label maintainer=sysadmin@local.domain \
    --name v2ray \
    --network cluster \
    --publish 6666:6666 \
    --restart always \
    --volume /srv/v2ray/config.json:/etc/v2ray/config.json \
    v2ray/official v2ray -config=/etc/v2ray/config.json

docker image prune --force
docker container logs v2ray
