#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

if [ -n "$(docker container ls --all --filter name='^/node-exporter$' --format '.')" ]; then
    docker container stop node-exporter
    docker container rm --volumes node-exporter
fi

docker run \
    --detach \
    --label maintainer=sysadmin@local.domain \
    --name node-exporter \
    --net 'host' \
    --pid 'host' \
    --restart always \
    --volume '/:/host:ro,rslave' \
    prom/node-exporter --path.rootfs '/host' --web.listen-address '172.24.0.1:10101'

docker image prune --force
docker container logs node-exporter
