#!/bin/bash

if (( EUID != 0 )); then
    echo "✗ This script must be run as root" 1>&2
    exit 1
fi

NAME='node-exporter'

if [ -n "$(docker container ls --all --filter name='^/'${NAME}'$' --format '.')" ]; then
    docker container stop "${NAME}"
    docker container rm --volumes "${NAME}"
fi

docker run \
    --detach \
    --label maintainer=sysadmin@local.domain \
    --name "${NAME}" \
    --net 'host' \
    --pid 'host' \
    --restart always \
    --volume '/:/host:ro,rslave' \
    prom/node-exporter --path.rootfs '/host' --web.listen-address '172.24.0.1:10101'

docker image prune --force
docker container logs "${NAME}"
