#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

certbot revoke \
    --cert-path "/etc/letsencrypt/live/${1}/fullchain.pem" \
    --delete-after-revoke \
    --reason superseded
