#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

certbot certonly \
    --domains "${1}" \
    --manual \
    --manual-public-ip-logging-ok \
    --preferred-challenges dns \
    --renew-by-default \
    --rsa-key-size 4096
