#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR

if (( EUID != 0 )); then
    echo '✗ This script must be run as root' 1>&2
    exit 1
fi

while (( $# > 0 )); do
    case "${1}" in
    -h | --help)
        cat << EOF
Usage:
    ${0##*/} [OPTION]... MODE DOMAIN

Optional arguments:
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit

Positional arguments:
    MODE (request | revoke)
        certificate provision mode
    DOMAIN
        domain name to apply
EOF
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

: "${1?✗ argument parsing failed: missing positional argument ‘MODE’}"
case "${1}" in
request | revoke)
    MODE=${1}
    ;;
*)
    echo "✗ argument parsing failed: acceptable values for ‘MODE’ are request | revoke" 1>&2
    exit 1
    ;;
esac
DOMAIN=${2?✗ argument parsing failed: missing positional argument ‘DOMAIN’}
shift 2

if (( $# > 0 )); then
    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
    exit 1
fi

if [ "${MODE}" = request ]; then
    certbot certonly \
        --domains "${DOMAIN}" \
        --manual \
        --manual-public-ip-logging-ok \
        --preferred-challenges dns \
        --renew-by-default \
        --rsa-key-size 4096
else
    certbot revoke \
        --cert-path "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" \
        --delete-after-revoke \
        --reason superseded
fi
