#!/bin/bash

if (( EUID != 0 )); then
    echo "This script must be run as root" 1>&2
    exit 1
fi

if [ "${OSTYPE}" != 'linux-gnu' ]; then
    echo "unknown os type: ${OSTYPE}" 1>&2
    exit 1
fi

DISTRO=$(awk -F '=' '/^ID=/ { print $2; exit }' /etc/os-release)

case "${DISTRO}" in
    arch)
        mkinitcpio -p linux
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;
    fedora)
        dracut --force --verbose
        grub2-mkconfig -o /boot/grub2/grub.cfg
        ;;
    kali | ubuntu)
        update-initramfs -k all -u
        grub-mkconfig -o /boot/grub/grub.cfg
        ;;
    *)
        echo "unknown distro: ${DISTRO}" 1>&2
        exit 1
        ;;
esac
