#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

trap 'echo ✗ fatal error: errexit trapped with status $? 1>&2' ERR

if (( EUID != 0 )); then
    echo '✗ This script must be run as root' 1>&2
    exit 1
fi

while (( $# > 0 )); do
    case "${1}" in
        -h | --help)
            cat << EOF
Usage:
    ${0##*/} [OPTION]...

Optional arguments:
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
            shift
            exit
            ;;
        -v | --version)
            echo v0.1.0
            shift
            exit
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
done

if (( $# > 0 )); then
    echo "✗ argument parsing failed: unrecognizable argument ‘${1}’" 1>&2
    exit 1
fi

if [ "${OSTYPE}" != linux-gnu ]; then
    echo "✗ unknown os type: ‘${OSTYPE}’" 1>&2
    exit 1
fi

# shellcheck disable=SC1090
source <(grep '^ID=' /etc/os-release)
DISTRO=${ID:-linux}

case "${DISTRO}" in
    arch | manjaro)
        mkinitcpio --allpresets
        grub-mkconfig --output /boot/grub/grub.cfg
        ;;
    fedora)
        dracut --force --regenerate-all --verbose
        if [ -d /sys/firmware/efi ]; then
            grub2-mkconfig --output /boot/efi/EFI/fedora/grub.cfg
        else
            grub2-mkconfig --output /boot/grub2/grub.cfg
        fi
        ;;
    kali | ubuntu)
        update-initramfs -k all -u
        grub-mkconfig --output /boot/grub/grub.cfg
        ;;
    opensuse*)
        dracut --force --regenerate-all
        grub2-mkconfig --output /boot/grub2/grub.cfg
        ;;
    *)
        echo "✗ unknown distro: ‘${DISTRO}’" 1>&2
        exit 1
        ;;
esac
