#!/bin/bash

if (( EUID != 0 )); then
    echo "✗ This script must be run as root" 1>&2
    exit 1
fi

if [ "${OSTYPE}" != 'linux-gnu' ]; then
    echo "✗ unknown os type: ‘${OSTYPE}’" 1>&2
    exit 1
fi

DISTRO=$(awk --field-separator '=' '/^ID=/ { print $2; exit }' /etc/os-release)

case "${DISTRO}" in
    arch)
        echo '------ [ package ] ------'
        pacman --query --foreign | sed 's/$/ [foreign]/g' | column -t
        pacman --query --deps --unrequired | sed 's/$/ [orphan]/g' | column -t
        echo '------ [ configuration ] ------'
        find /etc -type f -iregex '.+\.pac\(new\|save\)' -print0 | sort --zero-terminated | tr '\0' '\n'
        ;;
    fedora)
        echo '------ [ package ] ------'
        dnf --cacheonly --quiet list --extras
        dnf --cacheonly --quiet list --obsoletes
        echo '------ [ configuration ] ------'
        find /etc -type f -iregex '.+\.rpm\(new\|save\)' -print0 | sort --zero-terminated | tr '\0' '\n'
        ;;
    kali | ubuntu)
        echo '------ [ package ] ------'
        apt list 2> /dev/null | grep '\<\(local\|residual-config\)\]' | column -t
        apt search '\<(dummy|transitional)\>' 2> /dev/null | grep '\[installed\>' | column -t
        echo '------ [ configuration ] ------'
        find /etc -type f \( -iregex '.+\.dpkg-\(dist\|new\|old\)' -o -iregex '.+\.ucf-\(dist\|new\|old\)' \) -print0 | sort --zero-terminated | tr '\0' '\n'
        dpkg-query --show --showformat '${Package}\n${Conffiles}\n' | awk '/^[^ ]/{pkg=$1}/ obsolete$/{print pkg,$0}' | column -t
        ;;
    *)
        echo "✗ unknown distro: ‘${DISTRO}’" 1>&2
        exit 1
        ;;
esac
