#!/bin/bash

if (( EUID != 0 )); then
    echo "✗ This script must be run as root" 1>&2
    exit 1
fi

if [ "${OSTYPE}" != 'linux-gnu' ]; then
    echo "✗ unknown os type: ‘${OSTYPE}’" 1>&2
    exit 1
fi

# shellcheck disable=SC1090
source <(grep '^ID=' /etc/os-release)
DISTRO=${ID:-linux}

case "${DISTRO}" in
    arch | manjaro)
        echo '------ [ package ] ------'
        pacman --query --foreign | sed 's/$/ [foreign]/g' | column -t
        pacman --query --deps --unrequired | sed 's/$/ [orphan]/g' | column -t
        echo '------ [ configuration ] ------'
        find /etc -type f -iregex '.+\.\(old\|pac\(new\|save\)\)' -print0 | sort --zero-terminated | tr '\0' '\n'
        ;;
    fedora)
        echo '------ [ package ] ------'
        dnf --disableexcludes all --quiet list --extras
        dnf --disableexcludes all --quiet list --obsoletes
        dnf --disableexcludes all --quiet repoquery --duplicates
        echo '------ [ configuration ] ------'
        find /etc -type f -iregex '.+\.\(old\|rpm\(new\|save\)\)' -print0 | sort --zero-terminated | tr '\0' '\n'
        ;;
    kali | ubuntu)
        echo '------ [ package ] ------'
        apt list 2> /dev/null | grep '\<\(local\|residual-config\)\]' | column -t
        apt search '\<(dummy|transitional)\>' 2> /dev/null | grep '\[installed\>' | column -t
        echo '------ [ configuration ] ------'
        find /etc -type f \( -iregex '.+\.dpkg-\(dist\|new\|old\)' -o -iregex '.+\.old' -o -iregex '.+\.ucf-\(dist\|new\|old\)' \) -print0 | sort --zero-terminated | tr '\0' '\n'
        dpkg-query --show --showformat '${Package}\n${Conffiles}\n' | awk '/^[^ ]/{pkg=$1}/ obsolete$/{print pkg,$0}' | column -t
        ;;
    opensuse*)
        echo '------ [ package ] ------'
        zypper packages --orphaned
        zypper packages --unneeded
        echo '------ [ configuration ] ------'
        find /etc -type f -iregex '.+\.\(old\|rpm\(new\|save\)\)' -print0 | sort --zero-terminated | tr '\0' '\n'
        ;;
    *)
        echo "✗ unknown distro: ‘${DISTRO}’" 1>&2
        exit 1
        ;;
esac
