advertise-address: 172.31.0.10
default-local-storage-path: /mnt/k3s-local-storage
disable:
  - traefik
disable-helm-controller: true
disable-kube-proxy: true
disable-network-policy: true
flannel-backend: none
kubelet-arg:
  - config=/etc/rancher/k3s/kubelet.yaml
node-ip: 172.31.0.10
