#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

warn () {
    if (( $# > 0 )); then
        echo "${@}" 1>&2
    fi
}

die () {
    warn "${@}"
    exit 1
}

notify () {
    local code=$?
    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
}

trap notify ERR

display_help () {
    cat << EOF
Synopsis:
    ${0##*/} [OPTION]...

Options:
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
}

# shellcheck disable=SC1090
source "$(git -C "$(dirname "$(realpath "${0}")")" rev-parse --show-toplevel)/.privacy/digitalocean.cfg"

while (( $# > 0 )); do
    case ${1} in
    -h | --help)
        display_help
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

if (( $# > 0 )); then
    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
fi

clean_up () {
    true
}

trap clean_up EXIT

curl --fail --location --silent --show-error --request POST \
    --header "Authorization: Bearer ${AUTH_TOKEN}" \
    --header 'Content-Type: application/json' \
    --data @- << 'EOF' \
    "https://api.digitalocean.com/v2/domains/${DOMAIN}/records" \
    | python3 -m json.tool

{
    "type": "TXT",
    "name": "@",
    "data": "Schrodinger's Cat | Existence Precedes Essence",
    "priority": null,
    "port": null,
    "ttl": 3600,
    "weight": null,
    "flags": null,
    "tag": null
}
EOF
