#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

warn () {
    if (( $# > 0 )); then
        echo "${@}" 1>&2
    fi
}

die () {
    warn "${@}"
    exit 1
}

notify () {
    local code=$?
    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
}

trap notify ERR

display_help () {
    cat << EOF
Synopsis:
    ${0##*/} [OPTION]...

Options:
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
}

while (( $# > 0 )); do
    case ${1} in
    -h | --help)
        display_help
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

if (( $# > 0 )); then
    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
fi

if (( EUID != 0 )); then
    die '✗ This script must be run as root'
fi

clean_up () {
    true
}

trap clean_up EXIT

OS=$(uname -s)

case ${OS} in
Linux | FreeBSD)
    # shellcheck source=/dev/null
    source <(grep '^ID=' /etc/os-release)
    DISTRO=${ID:-linux}
    ;;
*)
    die "✗ unknown os: ‘${OS}’"
esac

case ${DISTRO} in
alpine)
    mkinitfs
    grub-mkconfig --output /boot/grub/grub.cfg
    ;;
arch | archarm | artix)
    mkinitcpio --allpresets
    grub-mkconfig --output /boot/grub/grub.cfg
    ;;
fedora)
    dracut --force --regenerate-all --verbose
    grub2-mkconfig --output /boot/grub2/grub.cfg
    ;;
gentoo)
    #emerge --ask @module-rebuild
    #emerge --config sys-kernel/gentoo-kernel-bin
    dracut --force --regenerate-all --verbose
    grub-mkconfig --output /boot/grub/grub.cfg
    ;;
kali)
    update-initramfs -c -k all
    grub-mkconfig --output /boot/grub/grub.cfg
    ;;
void)
    dracut --force --regenerate-all --verbose
    grub-mkconfig --output /boot/grub/grub.cfg
    ;;
*)
    die "✗ unknown distro: ‘${DISTRO}’"
    ;;
esac
