#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

warn () {
    if (( $# > 0 )); then
        echo "${@}" 1>&2
    fi
}

die () {
    warn "${@}"
    exit 1
}

notify () {
    local code=$?
    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
}

trap notify ERR

display_help () {
    cat << EOF
Synopsis:
    ${0##*/} [OPTION]...

Options:
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
}

while (( $# > 0 )); do
    case ${1} in
    -h | --help)
        display_help
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

if (( $# > 0 )); then
    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
fi

if (( EUID != 0 )); then
    die '✗ This script must be run as root'
fi

clean_up () {
    true
}

trap clean_up EXIT

OS=$(uname -s)

case ${OS} in
Linux | FreeBSD)
    # shellcheck source=/dev/null
    source <(grep '^ID=' /etc/os-release)
    DISTRO=${ID:-linux}
    ;;
*)
    die "✗ unknown os: ‘${OS}’"
esac

case ${DISTRO} in
alpine)
    echo ------ [ package ] ------
    apk list --orphaned
    echo ------ [ configuration ] ------
    find /etc -type f -iregex '.*/.+\.\(old\|apk-\(new\)\)' -print0 | sort --zero-terminated | tr '\0' '\n'
    ;;
arch | archarm | artix)
    echo ------ [ package ] ------
    { pacman --query --foreign || true; } | sed 's/$/ [foreign]/' | column --table
    { pacman --query --deps --unrequired || true; } | sed 's/$/ [orphan]/' | column --table
    echo ------ [ configuration ] ------
    find /etc -type f -iregex '.*/.+\.\(old\|pac\(new\|save\)\)' -print0 | sort --zero-terminated | tr '\0' '\n'
    ;;
fedora)
    echo ------ [ package ] ------
    dnf --disableexcludes all --quiet list --extras
    dnf --disableexcludes all --quiet list --obsoletes
    dnf --disableexcludes all --quiet repoquery --duplicates
    echo ------ [ configuration ] ------
    find /etc -type f -iregex '.*/.+\.\(old\|rpm\(new\|save\)\)' -print0 | sort --zero-terminated | tr '\0' '\n'
    ;;
gentoo)
    echo ------ [ configuration ] ------
    find /etc -iregex '.*/\._cfg[0-9][0-9][0-9][0-9]_.+' -print0 | sort --zero-terminated | tr '\0' '\n'
    ;;
kali)
    echo ------ [ package ] ------
    apt list 2>/dev/null | (grep '\<\(local\|residual-config\)\]' || true) | column --table
    apt search '\<(dummy|transitional)\>' 2>/dev/null | (grep '\[installed\>' || true) | column --table
    echo ------ [ configuration ] ------
    find /etc -type f \( -iregex '.*/.+\.dpkg-\(dist\|new\|old\)' -o -iregex '.*/.+\.old' -o -iregex '.*/.+\.ucf-\(dist\|new\|old\)' \) -print0 | sort --zero-terminated | tr '\0' '\n'
    dpkg-query --show --showformat '${Package}\n${Conffiles}\n' | awk '/^[^ ]/{pkg=$1}/ obsolete$/{print pkg,$0}' | column --table
    echo ------ [ recommend ] ------
    aptitude search --display-format '%c %p' '~RBrecommends:~i'
    ;;
void)
    echo ------ [ package ] ------
    xbps-query --list-orphans
    for pkg in /var/cache/xbps/*.xbps; do
        if ! xbps-query --property pkgver "$(xbps-uhelper binpkgver "${pkg}")" 1>/dev/null 2>&1; then
            printf '%s\n' "${pkg}"{,.sig2}
        fi
    done
    echo ------ [ configuration ] ------
    find /etc -type f -iregex '.*/.+\.\(old\|new-.+\)' -print0 | sort --zero-terminated | tr '\0' '\n'
    ;;
freebsd)
    echo ------ [ package ] ------
    pkg orphans --no-repo-update
    ;;
openbsd)
    echo ------ [ package ] ------
    pkg_delete -a -n
    ;;
*)
    die "✗ unknown distro: ‘${DISTRO}’"
    ;;
esac
