#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

warn () {
    if (( $# > 0 )); then
        echo "${@}" 1>&2
    fi
}

die () {
    warn "${@}"
    exit 1
}

notify () {
    local code=$?
    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
}

trap notify ERR

display_help () {
    cat << EOF
Synopsis:
    ${0##*/} [OPTION]...

Options:
    -f, --force
        force synchronization of package metadata (default: ${FORCE_SYNC})
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
}

FORCE_SYNC=false

while (( $# > 0 )); do
    case ${1} in
    -f | --force)
        FORCE_SYNC=true
        shift
        ;;
    -h | --help)
        display_help
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

if (( $# > 0 )); then
    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
fi

if (( EUID != 0 )); then
    die '✗ This script must be run as root'
fi

clean_up () {
    true
}

trap clean_up EXIT

OS=$(uname -s)

case ${OS} in
Linux|FreeBSD)
    # shellcheck source=/dev/null
    source <(grep '^ID=' /etc/os-release)
    DISTRO=${ID:-linux}
    ;;
*)
    die "✗ unknown os: ‘${OS}’"
esac

case ${DISTRO} in
arch|archarm)
    if [[ "${FORCE_SYNC}" = true ]]; then
        { yes || true; } | pacman --sync --clean --clean
        pacman --sync --refresh --refresh
    fi
    pacman --sync --refresh --sysupgrade
    pacman --query --deps --unrequired --unrequired --quiet | pacman --remove --nosave --recursive --unneeded - || true
    { yes || true; } | pacman --sync --clean --clean
    ;;
fedora)
    if [[ "${FORCE_SYNC}" = true ]]; then
        dnf clean all
    fi
    dnf makecache
    dnf check-update --changelogs || true
    dnf upgrade
    dnf autoremove
    dnf clean packages
    ;;
kali)
    if [[ "${FORCE_SYNC}" = true ]]; then
        apt clean
    fi
    apt update
    apt list --upgradable
    apt full-upgrade --purge
    apt clean
    apt autoremove --purge
    ;;
freebsd)
    if [[ "${FORCE_SYNC}" = true ]]; then
        pkg update --force
    fi
    freebsd-update fetch
    if freebsd-update updatesready; then
        freebsd-update install
    fi
    pkg update
    pkg upgrade
    pkg autoremove
    pkg clean --all
    ;;
*)
    die "✗ unknown distro: ‘${DISTRO}’"
    ;;
esac
