#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail

warn () {
    if (( $# > 0 )); then
        echo "${@}" 1>&2
    fi
}

die () {
    warn "${@}"
    exit 1
}

notify () {
    local code=$?
    warn "✗ [FATAL] $(caller): ${BASH_COMMAND} (${code})"
}

trap notify ERR

display_help () {
    cat << EOF
Synopsis:
    ${0##*/} [OPTION]...

Options:
    -f, --force
        force synchronization of package metadata (default: false)
    -h, --help
        show this help message and exit
    -v, --version
        output version information and exit
EOF
}

FORCE_SYNC=false

while (( $# > 0 )); do
    case ${1} in
    -f | --force)
        FORCE_SYNC=true
        shift
        ;;
    -h | --help)
        display_help
        shift
        exit
        ;;
    -v | --version)
        echo v0.1.0
        shift
        exit
        ;;
    --)
        shift
        break
        ;;
    *)
        break
        ;;
    esac
done

if (( $# > 0 )); then
    die "✗ argument parsing failed: unrecognizable argument ‘${1}’"
fi

if (( EUID != 0 )); then
    die '✗ This script must be run as root'
fi

clean_up () {
    true
}

trap clean_up EXIT

if [[ "${OSTYPE}" != linux-gnu ]] && [[ "${OSTYPE}" != linux ]]; then
    die "✗ unknown os type: ‘${OSTYPE}’"
fi

# shellcheck source=/dev/null
source <(grep '^ID=' /etc/os-release)
DISTRO=${ID:-linux}

case ${DISTRO} in
arch)
    if [[ "${FORCE_SYNC}" = true ]]; then
        { yes || true; } | pacman --sync --clean --clean
        pacman --sync --refresh --refresh
    fi
    pacman --sync --refresh --sysupgrade
    { yes || true; } | pacman --sync --clean --clean
    ;;
fedora)
    if [[ "${FORCE_SYNC}" = true ]]; then
        dnf clean all
    fi
    dnf makecache
    dnf check-update --changelogs || true
    dnf upgrade
    dnf autoremove
    dnf clean packages
    ;;
kali | ubuntu)
    if [[ "${FORCE_SYNC}" = true ]]; then
        apt clean
    fi
    apt update
    apt list --upgradable
    apt full-upgrade --purge
    apt clean
    apt autoremove --purge
    ;;
opensuse*)
    if [[ "${FORCE_SYNC}" = true ]]; then
        zypper clean --all
    fi
    zypper refresh
    zypper list-updates
    zypper dist-upgrade
    zypper purge-kernels
    zypper clean
    ;;
*)
    die "✗ unknown distro: ‘${DISTRO}’"
    ;;
esac
