apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
    advertiseAddress: 172.20.16.10
nodeRegistration:
    criSocket: /run/containerd/containerd.sock
    kubeletExtraArgs:
        node-ip: 172.20.16.10
---
apiVersion: kubeadm.k8s.io/v1beta3
controlPlaneEndpoint: k8s.cncf.site:6443
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.23.2
networking:
    podSubnet: 10.0.0.0/16
    serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
clusterDNS:
    - 10.96.0.10
kind: KubeletConfiguration
serverTLSBootstrap: true
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
nodePortAddresses:
    - 172.20.0.0/16
