apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
    advertiseAddress: 172.24.0.1
nodeRegistration:
    criSocket: /run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta2
controlPlaneEndpoint: k8s-raddest
kind: ClusterConfiguration
kubernetesVersion: v1.20.0
networking:
    podSubnet: 10.0.0.0/16
    serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
kind: KubeletConfiguration
